export const ErrorCode = {
  // Common
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',

  // Pharmacy
  PHARMACY_NOT_FOUND: 'PHARMACY_NOT_FOUND',

  // Medicine
  MEDICINE_NOT_FOUND: 'MEDICINE_NOT_FOUND',
  MEDICINE_ALREADY_EXISTS: 'MEDICINE_ALREADY_EXISTS',

  // Batch
  BATCH_NOT_FOUND: 'BATCH_NOT_FOUND',
  BATCH_ALREADY_EXISTS: 'BATCH_ALREADY_EXISTS',

  // Party
  PARTY_NOT_FOUND: 'PARTY_NOT_FOUND',

  // Purchase
  PURCHASE_NOT_FOUND: 'PURCHASE_NOT_FOUND',

  // Sales
  SALES_INVOICE_NOT_FOUND: 'SALES_INVOICE_NOT_FOUND',

  // Inventory
  STOCK_NOT_FOUND: 'STOCK_NOT_FOUND',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
