export const ErrorCode = {
  // Common
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',

  // Pharmacy
  PHARMACY_NOT_FOUND: 'PHARMACY_NOT_FOUND',

  // Medicine
  MEDICINE_NOT_FOUND: 'MEDICINE_NOT_FOUND',
  MEDICINE_ALREADY_EXISTS: 'MEDICINE_ALREADY_EXISTS',

  // Batch
  BATCH_NOT_FOUND: 'BATCH_NOT_FOUND',
  BATCH_ALREADY_EXISTS: 'BATCH_ALREADY_EXISTS',

  // Party
  PARTY_NOT_FOUND: 'PARTY_NOT_FOUND',
  PARTY_ROLE_NOT_FOUND: 'PARTY_ROLE_NOT_FOUND',
  PARTY_ADDRESS_NOT_FOUND: 'PARTY_ADDRESS_NOT_FOUND',
  PARTY_CONTACT_NOT_FOUND: 'PARTY_CONTACT_NOT_FOUND',
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  SUPPLIER_NOT_FOUND: 'SUPPLIER_NOT_FOUND',
  DOCTOR_NOT_FOUND: 'DOCTOR_NOT_FOUND',
  EMPLOYEE_NOT_FOUND: 'EMPLOYEE_NOT_FOUND',
  ENTITY_VERSION_CONFLICT: 'ENTITY_VERSION_CONFLICT',

  // Purchase
  PURCHASE_NOT_FOUND: 'PURCHASE_NOT_FOUND',

  // Sales
  SALES_INVOICE_NOT_FOUND: 'SALES_INVOICE_NOT_FOUND',

  // Inventory
  STOCK_NOT_FOUND: 'STOCK_NOT_FOUND',
  STOCK_INSUFFICIENT: 'STOCK_INSUFFICIENT',

  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  AUTH_PERMISSION_DENIED: 'AUTH_PERMISSION_DENIED',

  // Reporting
  REPORT_NOT_FOUND: 'REPORT_NOT_FOUND',
  REPORT_INVALID_DATE_RANGE: 'REPORT_INVALID_DATE_RANGE',
  REPORT_UNSUPPORTED_FORMAT: 'REPORT_UNSUPPORTED_FORMAT',

  // Persistence
  SEQUENCE_NOT_FOUND: 'SEQUENCE_NOT_FOUND',
  SEQUENCE_CONFLICT: 'SEQUENCE_CONFLICT',
  OUTBOX_DUPLICATE_OPERATION: 'OUTBOX_DUPLICATE_OPERATION',
  TRANSACTION_FAILED: 'TRANSACTION_FAILED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
