export const ErrorCode = {
  // Common
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',

  // Pharmacy
  PHARMACY_NOT_FOUND: 'PHARMACY_NOT_FOUND',

  // Medicine
  MEDICINE_NOT_FOUND: 'MEDICINE_NOT_FOUND',
  MEDICINE_ALREADY_EXISTS: 'MEDICINE_ALREADY_EXISTS',

  // Batch
  BATCH_NOT_FOUND: 'BATCH_NOT_FOUND',
  BATCH_ALREADY_EXISTS: 'BATCH_ALREADY_EXISTS',

  // Party
  PARTY_NOT_FOUND: 'PARTY_NOT_FOUND',
  PARTY_ROLE_NOT_FOUND: 'PARTY_ROLE_NOT_FOUND',
  PARTY_ADDRESS_NOT_FOUND: 'PARTY_ADDRESS_NOT_FOUND',
  PARTY_CONTACT_NOT_FOUND: 'PARTY_CONTACT_NOT_FOUND',
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  SUPPLIER_NOT_FOUND: 'SUPPLIER_NOT_FOUND',
  DOCTOR_NOT_FOUND: 'DOCTOR_NOT_FOUND',
  EMPLOYEE_NOT_FOUND: 'EMPLOYEE_NOT_FOUND',
  ENTITY_VERSION_CONFLICT: 'ENTITY_VERSION_CONFLICT',

  // Purchase
  PURCHASE_ORDER_NOT_FOUND: 'PURCHASE_ORDER_NOT_FOUND',
  PURCHASE_ORDER_ITEM_NOT_FOUND: 'PURCHASE_ORDER_ITEM_NOT_FOUND',
  GOODS_RECEIPT_NOT_FOUND: 'GOODS_RECEIPT_NOT_FOUND',
  GOODS_RECEIPT_ITEM_NOT_FOUND: 'GOODS_RECEIPT_ITEM_NOT_FOUND',
  PURCHASE_INVOICE_NOT_FOUND: 'PURCHASE_INVOICE_NOT_FOUND',
  PURCHASE_INVOICE_ITEM_NOT_FOUND: 'PURCHASE_INVOICE_ITEM_NOT_FOUND',
  PURCHASE_RETURN_NOT_FOUND: 'PURCHASE_RETURN_NOT_FOUND',
  PURCHASE_RETURN_ITEM_NOT_FOUND: 'PURCHASE_RETURN_ITEM_NOT_FOUND',
  PURCHASE_ORDER_NOT_RECEIVABLE: 'PURCHASE_ORDER_NOT_RECEIVABLE',
  GRN_PO_REQUIRED: 'GRN_PO_REQUIRED',
  RETURN_QUANTITY_EXCEEDED: 'RETURN_QUANTITY_EXCEEDED',
  SUPPLIER_INACTIVE: 'SUPPLIER_INACTIVE',

  // Sales
  SALES_INVOICE_NOT_FOUND: 'SALES_INVOICE_NOT_FOUND',
  SALES_INVOICE_ITEM_NOT_FOUND: 'SALES_INVOICE_ITEM_NOT_FOUND',
  SALES_PAYMENT_NOT_FOUND: 'SALES_PAYMENT_NOT_FOUND',
  SALES_RETURN_NOT_FOUND: 'SALES_RETURN_NOT_FOUND',
  SALES_RETURN_ITEM_NOT_FOUND: 'SALES_RETURN_ITEM_NOT_FOUND',
  PRICE_LIST_NOT_FOUND: 'PRICE_LIST_NOT_FOUND',
  PRICE_LIST_ITEM_NOT_FOUND: 'PRICE_LIST_ITEM_NOT_FOUND',
  BATCH_EXPIRED: 'BATCH_EXPIRED',
  INVOICE_NOT_POSTED: 'INVOICE_NOT_POSTED',
  CUSTOMER_REQUIRED_FOR_CREDIT: 'CUSTOMER_REQUIRED_FOR_CREDIT',
  PRESCRIPTION_NOT_FOUND: 'PRESCRIPTION_NOT_FOUND',

  // Inventory
  STOCK_NOT_FOUND: 'STOCK_NOT_FOUND',
  STOCK_INSUFFICIENT: 'STOCK_INSUFFICIENT',
  STOCK_MOVEMENT_NOT_FOUND: 'STOCK_MOVEMENT_NOT_FOUND',
  STOCK_ADJUSTMENT_NOT_FOUND: 'STOCK_ADJUSTMENT_NOT_FOUND',
  STOCK_ADJUSTMENT_ITEM_NOT_FOUND: 'STOCK_ADJUSTMENT_ITEM_NOT_FOUND',
  STOCK_TRANSFER_NOT_FOUND: 'STOCK_TRANSFER_NOT_FOUND',
  STOCK_TRANSFER_ITEM_NOT_FOUND: 'STOCK_TRANSFER_ITEM_NOT_FOUND',
  STOCK_TAKE_NOT_FOUND: 'STOCK_TAKE_NOT_FOUND',
  STOCK_TAKE_ITEM_NOT_FOUND: 'STOCK_TAKE_ITEM_NOT_FOUND',
  INVALID_DOCUMENT_STATUS: 'INVALID_DOCUMENT_STATUS',
  DOCUMENT_HAS_NO_ITEMS: 'DOCUMENT_HAS_NO_ITEMS',

  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  AUTH_PERMISSION_DENIED: 'AUTH_PERMISSION_DENIED',
  AUTH_MUST_CHANGE_PASSWORD: 'AUTH_MUST_CHANGE_PASSWORD',

  // Reporting
  REPORT_NOT_FOUND: 'REPORT_NOT_FOUND',
  REPORT_INVALID_DATE_RANGE: 'REPORT_INVALID_DATE_RANGE',
  REPORT_UNSUPPORTED_FORMAT: 'REPORT_UNSUPPORTED_FORMAT',

  // Finance
  LEDGER_NOT_FOUND: 'LEDGER_NOT_FOUND',
  LEDGER_INACTIVE: 'LEDGER_INACTIVE',
  LEDGER_IS_SYSTEM: 'LEDGER_IS_SYSTEM',
  LEDGER_HAS_CHILDREN: 'LEDGER_HAS_CHILDREN',
  LEDGER_CIRCULAR_HIERARCHY: 'LEDGER_CIRCULAR_HIERARCHY',
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  RECEIPT_NOT_FOUND: 'RECEIPT_NOT_FOUND',
  FINANCIAL_YEAR_CLOSED: 'FINANCIAL_YEAR_CLOSED',
  VOUCHER_UNBALANCED: 'VOUCHER_UNBALANCED',

  // Persistence
  SEQUENCE_NOT_FOUND: 'SEQUENCE_NOT_FOUND',
  SEQUENCE_CONFLICT: 'SEQUENCE_CONFLICT',
  OUTBOX_DUPLICATE_OPERATION: 'OUTBOX_DUPLICATE_OPERATION',
  TRANSACTION_FAILED: 'TRANSACTION_FAILED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
