export const DocumentType = {
  SALES_INVOICE: 'SALES_INVOICE',
  SALES_PAYMENT: 'SALES_PAYMENT',
  SALES_RETURN: 'SALES_RETURN',
  GOODS_RECEIPT: 'GOODS_RECEIPT',
  PURCHASE_ORDER: 'PURCHASE_ORDER',
  STOCK_MOVEMENT: 'STOCK_MOVEMENT',
  STOCK_ADJUSTMENT: 'STOCK_ADJUSTMENT',
  STOCK_TRANSFER: 'STOCK_TRANSFER',
  STOCK_TAKE: 'STOCK_TAKE',
  PURCHASE_INVOICE: 'PURCHASE_INVOICE',
  PURCHASE_RETURN: 'PURCHASE_RETURN',
  PAYMENT: 'PAYMENT',
  RECEIPT: 'RECEIPT',
} as const;

export type DocumentType = (typeof DocumentType)[keyof typeof DocumentType];

export const ResetPolicy = {
  NEVER: 'NEVER',
  YEARLY: 'YEARLY',
  MONTHLY: 'MONTHLY',
  DAILY: 'DAILY',
} as const;
