import type { PrismaClient } from '@prisma/client';

/** Delete in reverse FK order (children first). */
export const SEED_TABLES: (keyof PrismaClient)[] = [
  'idSequence',
  'syncConflict',
  'outbox',
  'syncLog',
  'changeHistory',
  'auditLog',
  'salesReturnItem',
  'salesReturn',
  'salesPayment',
  'salesInvoiceItem',
  'salesInvoice',
  'purchaseReturnItem',
  'purchaseReturn',
  'purchaseInvoiceItem',
  'purchaseInvoice',
  'goodsReceiptItem',
  'goodsReceipt',
  'purchaseOrderItem',
  'purchaseOrder',
  'stockTakeItem',
  'stockTake',
  'stockTransferItem',
  'stockTransfer',
  'stockAdjustmentItem',
  'stockAdjustment',
  'stockMovement',
  'stock',
  'prescriptionItem',
  'prescription',
  'loyaltyTransaction',
  'priceListItem',
  'discountRule',
  'medicineSalt',
  'batch',
  'medicine',
  'manufacturer',
  'userSession',
  'userRole',
  'userBranch',
  'user',
  'customer',
  'supplier',
  'doctor',
  'employee',
  'partyContact',
  'partyAddress',
  'partyRole',
  'party',
  'rolePermission',
  'role',
  'permission',
  'priceList',
  'tax',
  'loyaltyProgram',
  'ledgerEntry',
  'ledger',
  'payment',
  'receipt',
  'expense',
  'sequenceGenerator',
  'appSetting',
  'barcodeConfiguration',
  'printerConfiguration',
  'financialYear',
  'branch',
  'company',
  'area',
  'city',
  'state',
  'country',
  'saltComposition',
  'medicineGeneric',
  'medicineSchedule',
  'medicineCategory',
  'unitOfMeasure',
];

export async function wipeDatabase(prisma: PrismaClient): Promise<void> {
  for (const model of SEED_TABLES) {
    const delegate = prisma[model] as { deleteMany: () => Promise<unknown> };
    if (delegate?.deleteMany) {
      await delegate.deleteMany();
    }
  }
}
